### ISSUE TITLE
erroe when run video edit

### ISSUE THREAD

**Issue by jachenms** [LumingMelody/Ai-movie-clip#3]
<img width="2160" height="1440" alt="Image" src="https://github.com/user-attachments/assets/8e43d4d4-88e9-48e6-8399-af5e82523fb7" />

<img width="2160" height="1440" alt="Image" src="https://github.com/user-attachments/assets/90987dff-ce6a-4abd-954d-e299d0d18d58" />

**Comment by LumingMelody** [comment]
DashScope API Key

**Comment by jachenms** [comment]
<img width="2160" height="1440" alt="Image" src="https://github.com/user-attachments/assets/7f4101c0-b4aa-4e4e-8507-9572c0650a8f" />

env inlcude all api key, why always make a erroe

**Comment by LumingMelody** [comment]
> <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/155041854/476995357-7f4101c0-b4aa-4e4e-8507-9572c0650a8f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUwNTE3NjYsIm5iZiI6MTc1NTA1MTQ2NiwicGF0aCI6Ii8xNTUwNDE4NTQvNDc2OTk1MzU3LTdmNDEwMWMwLWI0YWEtNGU0ZS04NTA3LTk1NzJjMDY1MGE4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxM1QwMjE3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2EyNWEyZDMwYzcwZTYwYWRkZTI5ZWIwY2Q5OTg0NTk4ZTlkMTBmM2Y1NTljNGY3YzY5MzU4MzcxM2Y5ZTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZAKQJlwvO4A7q9SuXjR5MsLBbY2yZc53KHnPxvh90Fo">
> env inlcude all api key, why always make a erroe

Because I used both the get_api_key.py file and the .env file to obtain the DASHSCOPE_API_KEY. There are two methods for obtaining the API key. The get_api_key.py file needs to create an api_key.txt file. Now I will fix this and make sure to use the .env file for obtaining the configuration.

**Comment by jachenms** [comment]
<img width="2160" height="1440" alt="Image" src="https://github.com/user-attachments/assets/285b4c15-3802-41b2-b230-8c8bf4890c87" />
I have identified api key in .env, but still error

**Comment by jachenms** [comment]
<img width="2160" height="1440" alt="Image" src="https://github.com/user-attachments/assets/1ab21592-95d4-4b5d-8502-d5ea6b74b56f" />

appreciated to help me to fix the issue depending on updated error

**Comment by LumingMelody** [comment]
> <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/155041854/477547274-1ab21592-95d4-4b5d-8502-d5ea6b74b56f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUxMzQzNjEsIm5iZiI6MTc1NTEzNDA2MSwicGF0aCI6Ii8xNTUwNDE4NTQvNDc3NTQ3Mjc0LTFhYjIxNTkyLTk1ZDQtNGI1ZC04NTAyLWQ1ZWE2Yjc0YjU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNFQwMTE0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjQzZDY4Y2M3NTVjN2U1ZGY5NDY4MDMyMTEzNWY1MWU3MTM3YTRjODdlNGI4NDdhNTgxYWYzMTI3ZWZlNTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KNWM_8RAjt_aNdAeyBYQoIY_cr2A3DpXhu7Pgb-OShc">
> appreciated to help me to fix the issue depending on updated error

Is this the latest code? Just run "git pull" for me

🚀 [EXECUTE] 开始执行函数: get_video_edit_simple
🎬 开始视频编辑:
   视频源: ['https://files.cstlanbaai.com/probe-material/202507/24/16/611a1b597bad461cb69b079c291000d8.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=zklb%2F20250814%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250814T011836Z&X-Amz-Expires=18480&X-Amz-SignedHeaders=host&X-Amz-Signature=a8147585b9629f80d52281a0ca82be9dea90f7be579924d3c9fec9a8589a1f61']
   目标时长: 30秒
   风格: 抖音风
MoviePy 版本: 2.1.2
INFO:     127.0.0.1:54427 - "POST /video/edit HTTP/1.1" 200 OK
✅ FFmpeg 可用
⬇️ 开始下载文件: https://files.cstlanbaai.com/probe-material/202507/24/16/611a1b597bad461cb69b079c291000d8.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=zklb%2F20250814%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250814T011836Z&X-Amz-Expires=18480&X-Amz-SignedHeaders=host&X-Amz-Signature=a8147585b9629f80d52281a0ca82be9dea90f7be579924d3c9fec9a8589a1f61
📥 下载进度: 100.0%
✅ 文件下载完成: /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4
📊 文件大小: 9.67MB
📁 处理后的路径: ['/var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4']
✅ 找到有效视频: smart_clip_kbpm4c_8.mp4
✅ 成功导入特效模块
🚀 开始AI视频自动剪辑流程...

📋 步骤1: 视频识别与预处理
  单个视频: smart_clip_kbpm4c_8.mp4

📋 步骤2: 内容分析与分类

🔍 没有提供分析结果，开始重新分析...
    尝试导入: analyzer.video_analyzer
2025-08-14 09:19:11,033 - INFO - 成功导入特效模块
[cozepy][INFO][2025-08-14 09:19:11] 成功导入特效模块
✅ 成功导入: analyzer.video_analyzer
  分析视频: smart_clip_kbpm4c_8.mp4
[+] 正在分析视频: /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4
[+] 正在提取基础信息...
2025-08-14 09:19:11,598 - INFO - 成功导入: analyzer.video_analyzer
[cozepy][INFO][2025-08-14 09:19:11] 成功导入: analyzer.video_analyzer
[+] 正在进行场景检测...
[+] 使用新版 PySceneDetect API 进行场景检测...
[cozepy][INFO][2025-08-14 09:19:11] Detecting scenes...
[+] 检测到 0 个场景
[+] 提取音频并进行语音识别...
[+] 加载Whisper模型...
[+] Whisper模型加载成功
[+] 使用Whisper进行语音识别...
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/whisper/transcribe.py:126: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
[+] Whisper识别成功: 因為風險其實越來越大那麼有一些我們的財務人員專制的財務人員在專業度也好在一些跟稅務的應對的風險方面各方面其實能力還是存在的大差距那麼我們市務所一托就是具有什麼的稅務所 快擊市務所 一起花優勢我們公司呢...

🎙️ 语音识别句子级时间戳:
==================================================
[ 1] 00:00.00 - 00:01.36 | 因為風險其實越來越大
[ 2] 00:02.20 - 00:04.56 | 那麼有一些我們的財務人員
[ 3] 00:04.56 - 00:07.18 | 專制的財務人員在專業度也好
[ 4] 00:07.18 - 00:10.24 | 在一些跟稅務的應對的風險方面
[ 5] 00:10.24 - 00:12.90 | 各方面其實能力還是存在的大差距
[ 6] 00:13.50 - 00:15.00 | 那麼我們市務所一托
[ 7] 00:15.00 - 00:17.20 | 就是具有什麼的
[ 8] 00:17.20 - 00:20.12 | 稅務所 快擊市務所 一起花優勢
[ 9] 00:20.12 - 00:22.60 | 我們公司呢 就是在這個
[10] 00:23.58 - 00:25.46 | 就是稅務跟財務領域
[11] 00:25.46 - 00:28.90 | 就是已經應該說有多年的一個
[12] 00:28.90 - 00:29.78 | 豐富的一個
[13] 00:29.78 - 00:31.92 | 我們公司呢 現在是
[14] 00:32.50 - 00:34.18 | 就是根據目前的情況
[15] 00:34.18 - 00:36.86 | 就是財政現在壓力比較大
[16] 00:36.86 - 00:39.52 | 那麼財政我們的那個
[17] 00:39.52 - 00:43.22 | 去稅收 賺財政收入的80%
==================================================

📊 语音片段分析 (目标时长: 30秒):
--------------------------------------------------
🎯 最佳语音片段推荐:
  1. 00:17.20 - 00:43.22 (时长: 24.5s, 密度: 0.6 词/秒)
     内容预览: 稅務所 快擊市務所 一起花優勢...
  2. 00:13.50 - 00:43.22 (时长: 28.2s, 密度: 0.6 词/秒)
     内容预览: 那麼我們市務所一托...
  3. 00:15.00 - 00:43.22 (时长: 26.7s, 密度: 0.6 词/秒)
     内容预览: 就是具有什麼的...

📊 时间戳数据摘要:
  - 句子数量: 17
  - 总时长: 43.2秒
  - 平均句长: 10.8字/句
[+] 进行对象检测...
[+] 加载YOLO模型...

video 1/1 (frame 1/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 39.3ms
video 1/1 (frame 2/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 34.7ms
video 1/1 (frame 3/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 34.3ms
video 1/1 (frame 4/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 31.2ms
video 1/1 (frame 5/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 31.8ms
video 1/1 (frame 6/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 33.8ms
video 1/1 (frame 7/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 35.7ms
video 1/1 (frame 8/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 32.3ms
video 1/1 (frame 9/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 32.0ms
video 1/1 (frame 10/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 31.3ms
video 1/1 (frame 11/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 31.8ms
video 1/1 (frame 12/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 33.7ms
video 1/1 (frame 13/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 33.1ms
video 1/1 (frame 14/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 32.2ms
video 1/1 (frame 15/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 32.4ms
video 1/1 (frame 16/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 33.0ms
video 1/1 (frame 17/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 32.3ms
video 1/1 (frame 18/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 31.1ms
video 1/1 (frame 19/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 32.3ms
video 1/1 (frame 20/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 29.2ms
video 1/1 (frame 21/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 32.2ms
video 1/1 (frame 22/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 32.2ms
video 1/1 (frame 23/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 31.5ms
video 1/1 (frame 24/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 32.9ms
video 1/1 (frame 25/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 34.7ms
video 1/1 (frame 26/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 33.5ms
video 1/1 (frame 27/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 33.7ms
video 1/1 (frame 28/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 35.7ms
video 1/1 (frame 29/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 36.1ms
video 1/1 (frame 30/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 34.8ms
video 1/1 (frame 31/1350) /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8.mp4: 640x384 1 person, 1 wine glass, 1 dining table, 34.2ms
[+] 检测是否有人脸...
[+] 进行内容分类...
[+] 简化时间戳信息已保存到: /var/folders/5k/_xpqn2rx06q47l0lv3lq16z40000gn/T/smart_clip_kbpm4c_8_timestamps.json
✅ 视频分析完成

📊 分析结果摘要:
  - 视频时长: 45.0秒
  - 内容类型: 人声剧情类
  - 语音句子数: 17
  - 精彩片段数: 3
    内容类型: 人声剧情类

📋 步骤3: 剪辑策略生成
  为视频 1 生成策略...
    📊 策略生成完成，包含 1 个操作

📋 步骤4: 执行剪辑操作
  剪辑视频 1: smart_clip_kbpm4c_8.mp4
    📥 安全加载视频: smart_clip_kbpm4c_8.mp4
    📊 视频信息:
      - 文件: smart_clip_kbpm4c_8.mp4
      - 时长: 45.0秒
      - 分辨率: 1080x1920
      - FPS: 30.0
      - 音频: 有
    📋 策略类型: single_segment
    📋 操作数量: 1
    ✂️ 执行单片段策略
    🔧 执行剪辑: 0.0s - 30.0s (时长: 30.0s)
    ✅ 单片段剪辑成功 (含音频): 30.0s
    ✅ 完成剪辑，最终时长: 30.0秒

📋 步骤5: 输出最终视频
  📊 输出前检查:
    - 时长: 30.0秒
    - 分辨率: 1080x1920
    - FPS: 30.0
    - 音频: 有
  🔄 开始安全输出...
  🎵 音频输出已启用
  ✅ 视频输出成功！

  📁 完全修复版输出验证:
    - 文件: /Users/luming/PycharmProjects/Ai-movie-clip/ikun/video_edit_output/b4a77f59-265f-46b9-a298-5931de1b6874/edited_video.mp4
    - 大小: 5.79MB
🎉 视频编辑完成: {'status': 'success', 'output_video': '/Users/luming/PycharmProjects/Ai-movie-clip/ikun/video_edit_output/b4a77f59-265f-46b9-a298-5931de1b6874/edited_video.mp4', 'file_size_mb': 5.79, 'video_info': {'duration': 30, 'resolution': '1080x1920', 'fps': 30.0, 'has_audio': True}, 'processing_time': 42.57}
✅ 编辑成功，输出路径: video_edit_output/b4a77f59-265f-46b9-a298-5931de1b6874/edited_video.mp4
✅ [EXECUTE] 函数执行完成: get_video_edit_simple, 耗时: 43.34s
☁️ [OSS-UPLOAD] 处理结果并更新状态
🔍 提取warehouse路径，输入结果类型: <class 'str'>, 内容: video_edit_output/b4a77f59-265f-46b9-a298-5931de1b6874/edited_video.mp4
✅ 最终warehouse路径: video_edit_output/b4a77f59-265f-46b9-a298-5931de1b6874/edited_video.mp4

**Comment by jachenms** [comment]
<img width="2160" height="1440" alt="Image" src="https://github.com/user-attachments/assets/d7d9646a-c8ec-4440-b43d-ef7698031b3e" />

after pull git, but ir is still error

**Comment by LumingMelody** [comment]
> <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/155041854/477869474-d7d9646a-c8ec-4440-b43d-ef7698031b3e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUxNTMzMDksIm5iZiI6MTc1NTE1MzAwOSwicGF0aCI6Ii8xNTUwNDE4NTQvNDc3ODY5NDc0LWQ3ZDk2NDZhLWM4ZWMtNDQ0MC1iNDNkLWVmNzY5ODAzMWIzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNFQwNjMwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjZmYWUzYjllOTEyMWEzMDRkZGJjYTgyZDYxZGEyZDM5OTdlYTcyZmNmN2NiZTg1ZWIyYjNhMThlOTU2NzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MfKfCKJZ4xMmVdz3RRGN7huWwyqUoPsJjk8xkZzuNkM">
> after pull git, but ir is still error

There is an issue with the function definition on line 317 of workflow_orchestrator.py. I have fixed it and uploaded it

**Comment by jachenms** [comment]
<img width="2160" height="1440" alt="Image" src="https://github.com/user-attachments/assets/c5cc660d-0f8f-4245-8bb0-51a8d74625f6" />

<img width="2160" height="1440" alt="Image" src="https://github.com/user-attachments/assets/e850d46d-ebb8-448d-81ea-c4effd30683a" />

when run uvcorn  app.py, still have a error

**Comment by LumingMelody** [comment]
> <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/155041854/477932137-c5cc660d-0f8f-4245-8bb0-51a8d74625f6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUxNjI1MDYsIm5iZiI6MTc1NTE2MjIwNiwicGF0aCI6Ii8xNTUwNDE4NTQvNDc3OTMyMTM3LWM1Y2M2NjBkLTBmOGYtNDI0NS04YmIwLTUxYThkNzQ2MjVmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNFQwOTAzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDNhYjhhMmY1ODdjMzQzNWEwZjBmODExMjJiZTAxZjY3NTA5NDgzYmE5MmMzODQyNWU4ZDk1Y2JjOGM0MTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jLThyCLsIj3euLkdS8t-VLLd-TUI6kv4nMgUa5Zk-aE"> <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/155041854/477932464-e850d46d-ebb8-448d-81ea-c4effd30683a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUxNjI1MDYsIm5iZiI6MTc1NTE2MjIwNiwicGF0aCI6Ii8xNTUwNDE4NTQvNDc3OTMyNDY0LWU4NTBkNDZkLWViYjgtNDQ4ZC04MWVhLWM0ZWZmZDMwNjgzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNFQwOTAzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODVlNTBkNTA0MzM4NGFjMjFiZWVhNWUwMDMwODc4Mjk3NGZjN2U3MzQ2MjQxM2IxZWFjOTc4ZGU2Nzk5MThmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MjmENHc9vGTG6vUptVpQkhof0lr6oCYMedCem1TroxE">
> when run uvcorn app.py, still have a error

Create a "key.yaml" file in the root directory and then fill it in with the following content.

tongyi:
coze:
Corresponding key

I will update later to directly obtain the key from.env
